import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"; // Corrected import

export const metadata: Metadata = {
  title: "NeuraAdapt",
  description: "Generated by create next app",
};

const geist = Geist({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geist.className} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}

const NavBar = () => {
  return (
    <nav className="sticky top-0 z-40 w-full py-8 bg-white text-black px-20 flex justify-between">
      <p className="text-blue-600 font-bold text-2xl">NeuraAdapt</p>
      <Link href="/Learning">
        <span className="p-3 rounded-full bg-blue-600 text-white">Start Learning</span>
      </Link>
    </nav>
  );
};
